import Navbar from "@/components/Navbar";
import "../globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({
//   weight: "400",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <div>
      {/* <body className={roboto.className}> */}
      {/* {children} */}
      <Navbar />
      <div className="mx-auto h-full pt-16 bg-gray-100">{children}</div>

      {/* <div className="container max-w-7xl  mx-auto h-full pt-16">
          {children}
        </div> */}
      {/* </body> */}
      {/* </html> */}
    </div>
  );
}
